/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DataBase.TableAdmin;
import DataBase.TableOwner;
import javax.swing.JOptionPane;

/**
 *
 * @author mouloud
 */
public class LogIn extends javax.swing.JFrame {

    /**
     * Creates new form LogIn
     */
    public LogIn() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        AdminUsernameField1.setText("adminF.adminL");
        AdminPasswordField1.setText("admin");
        setDefaultCloseOperation(HIDE_ON_CLOSE);
        setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Admin1 = new javax.swing.JPanel();
        AdminUsernameLabel1 = new javax.swing.JLabel();
        AdminUsernameField1 = new javax.swing.JTextField();
        AdminPasswordLabel1 = new javax.swing.JLabel();
        AdminLoginButton1 = new javax.swing.JButton();
        AdminPasswordField1 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Admin1.setBackground(new java.awt.Color(255, 255, 255));

        AdminUsernameLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AdminUsernameLabel1.setText("Admin Username");

        AdminUsernameField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminUsernameField1ActionPerformed(evt);
            }
        });

        AdminPasswordLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AdminPasswordLabel1.setText("Admin Password");

        AdminLoginButton1.setText("Log In");
        AdminLoginButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminLoginButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel1.setText("Log In Page for Admin");

        javax.swing.GroupLayout Admin1Layout = new javax.swing.GroupLayout(Admin1);
        Admin1.setLayout(Admin1Layout);
        Admin1Layout.setHorizontalGroup(
            Admin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Admin1Layout.createSequentialGroup()
                .addGap(0, 75, Short.MAX_VALUE)
                .addGroup(Admin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(AdminPasswordField1)
                    .addComponent(AdminPasswordLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AdminUsernameLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AdminUsernameField1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AdminLoginButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        Admin1Layout.setVerticalGroup(
            Admin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Admin1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(AdminUsernameLabel1)
                .addGap(18, 18, 18)
                .addComponent(AdminUsernameField1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AdminPasswordLabel1)
                .addGap(30, 30, 30)
                .addComponent(AdminPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(AdminLoginButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Admin1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Admin1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AdminUsernameField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminUsernameField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminUsernameField1ActionPerformed

    private void AdminLoginButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminLoginButton1ActionPerformed
        // TODO add your handling code here:
         TableAdmin temp = new TableAdmin();
        boolean var = temp.ChercherData(AdminUsernameField1.getText(), AdminPasswordField1.getText());
        if (var == true){
            //JOptionPane.showMessageDialog(null,"Admin conneted");
             new Home().IdAdmin = new TableAdmin().getIdclientTableAdmin(AdminUsernameField1.getText());
            setVisible(false);
        }
        else
            JOptionPane.showMessageDialog(null,"Admin Erreur");
       
    }//GEN-LAST:event_AdminLoginButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Admin1;
    private javax.swing.JButton AdminLoginButton1;
    private javax.swing.JPasswordField AdminPasswordField1;
    private javax.swing.JLabel AdminPasswordLabel1;
    private javax.swing.JTextField AdminUsernameField1;
    private javax.swing.JLabel AdminUsernameLabel1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
