/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DataBase.TableOwner;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author mouloud
 */
public class LogInOwner extends javax.swing.JFrame {

    /**
     * Creates new form LogInOwner
     */
    public LogInOwner() {
        initComponents();
        ImageIcon icon = new ImageIcon(getClass().getResource("imgs/house.png"));
        this.setIconImage(icon.getImage());
        setResizable(false);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(HIDE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Owner = new javax.swing.JPanel();
        OwnerFirstNameLabel = new javax.swing.JLabel();
        OwnerFirstNameField = new javax.swing.JTextField();
        OwnerLastNameLabel = new javax.swing.JLabel();
        OwnerLastNameField = new javax.swing.JTextField();
        OwnerPasswordLabel = new javax.swing.JLabel();
        OwnerLogInButton = new javax.swing.JButton();
        OwnerPasswordField = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Owner.setBackground(new java.awt.Color(255, 255, 255));

        OwnerFirstNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        OwnerFirstNameLabel.setText("Owner First Name");

        OwnerFirstNameField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        OwnerLastNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        OwnerLastNameLabel.setText("Owner Last Name");

        OwnerLastNameField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        OwnerPasswordLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        OwnerPasswordLabel.setText("Owner Password");

        OwnerLogInButton.setBackground(new java.awt.Color(204, 255, 255));
        OwnerLogInButton.setText("Log In");
        OwnerLogInButton.setBorder(null);
        OwnerLogInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OwnerLogInButtonActionPerformed(evt);
            }
        });

        OwnerPasswordField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Log In Page for Owner");

        javax.swing.GroupLayout OwnerLayout = new javax.swing.GroupLayout(Owner);
        Owner.setLayout(OwnerLayout);
        OwnerLayout.setHorizontalGroup(
            OwnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OwnerLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(OwnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(OwnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(OwnerFirstNameField)
                        .addComponent(OwnerLastNameField)
                        .addComponent(OwnerFirstNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(OwnerLastNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(OwnerPasswordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(OwnerPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(OwnerLogInButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel1))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        OwnerLayout.setVerticalGroup(
            OwnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OwnerLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(OwnerFirstNameLabel)
                .addGap(27, 27, 27)
                .addComponent(OwnerFirstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OwnerLastNameLabel)
                .addGap(18, 18, 18)
                .addComponent(OwnerLastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(OwnerPasswordLabel)
                .addGap(18, 18, 18)
                .addComponent(OwnerPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(OwnerLogInButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 351, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(Owner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 371, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(Owner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OwnerLogInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OwnerLogInButtonActionPerformed
        // TODO add your handling code here:
        TableOwner temp = new TableOwner();
        boolean var = temp.ChercherData(OwnerFirstNameField.getText(), OwnerLastNameField.getText(), OwnerPasswordField.getText());
        if (var == true){
            setVisible(false);
            new AddAdmin();
        }

        else
        JOptionPane.showMessageDialog(null,"Owner Error");
    }//GEN-LAST:event_OwnerLogInButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Owner;
    private javax.swing.JTextField OwnerFirstNameField;
    private javax.swing.JLabel OwnerFirstNameLabel;
    private javax.swing.JTextField OwnerLastNameField;
    private javax.swing.JLabel OwnerLastNameLabel;
    private javax.swing.JButton OwnerLogInButton;
    private javax.swing.JPasswordField OwnerPasswordField;
    private javax.swing.JLabel OwnerPasswordLabel;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
